<?php
$pageTitle       = 'Terms & Conditions';
$metaDescription = 'Definitions Some of the words you’ll see have very specific meanings, so please check out the ‘RioRelax dictionary’ at the end of these Terms. About these terms...';
$canonicalPath   = 'terms-conditions';
$currentPage     = 'terms-conditions';
$isHome          = false;
$pageStyles      = <<<'CSS'
<style>.page_speed_d41d8cd98f00b204e9800998ecf8427e{} .page_speed_b6d718a4baf2d940c28646fbc7649f19{height: 16px; width: auto;} .page_speed_4f5fad078626002a7a56d8c6ce26b4e0{background-image: url('themes/travlla/images/background/inr-banner.jpg'); background-size: cover; background-position: center;} .page_speed_d5aa19c02ca93bd01f98683bd4c5813f{--cc-primary: #066168; --cc-primary-hover: #054c52; --cc-accent-text: #ffffff;}</style>
CSS;
include __DIR__ . '/includes/header.php';
?>
 <div  class="wt-bnr-inr overlay-wraper bg-center page_speed_4f5fad078626002a7a56d8c6ce26b4e0"> <div class="wt-bnr-inr-entry"> <div class="container"> <div class="banner-title-outer"> <div class="banner-title-name"> <h2 class="wt-title">Terms &amp; Conditions</h2> </div> <div> <ul class="wt-breadcrumb breadcrumb-style-2"> <li><a href="index.php" title="Home">Home</a></li> <li>Terms &amp; Conditions</li> </ul> </div> </div> </div> <div class="trv-inr-bnr-cloud"> <div class="marquee"><img width="587" height="196" data-dims-auto src=themes/travlla/images/decorations/banner-cloud.png alt="image"></div> </div> <div class="trv-inr-bnr-plane"> <div class="trv-inr-bnr-plane-bx"><img width="431" height="166" data-dims-auto src=themes/travlla/images/decorations/airplane.png alt="image"></div> </div> <div class="trv-inr-bnr-bloon-1"><img width="233" height="337" data-dims-auto src=themes/travlla/images/decorations/balloon-left.png alt="image"></div> <div class="trv-inr-bnr-bloon-2"><img width="110" height="166" data-dims-auto src=themes/travlla/images/decorations/balloon-right.png alt="image"></div> </div> </div> <div class="container page-default-content p-t100 p-b100"> <div class="ck-content"><div class="about-area5 about-p p-relative"> <div class="container pt-60 pb-90"> <div class="service-detail"> <div class="content-box"> <h3>Definitions</h3> <p>Some of the words you’ll see have very specific meanings, so please check out the ‘RioRelax dictionary’ at the end of these Terms.</p> <h3>About these terms</h3> <p>When you complete your Booking, you accept these Terms and any other terms that you’re provided with during the booking process.</p> <p>The English version of these Terms is the original. If there’s any dispute about the Terms, or any mismatch between the Terms in English and in another language, the Terms as they appear in English will apply. (You can change the language at the top of this page.</p> <h3>Our Platform</h3> <p> We take reasonable care in providing our Platform, but we can’t guarantee that everything on it is accurate (we get information from the Service Providers). To the extent permitted by law, we can’t be held responsible for any errors, any interruptions, or any missing bits of information - although we will do everything we can to correct/fix them as soon as we can.</p> <p>We will show you the offers that are available to you, in (what we think is) the right language for you. You can change to another language whenever you like.</p> <h3>Prices</h3> <p> When you make a Booking, you agree to pay the cost of the Travel Experience, including any charges and taxes that may apply.</p> <p> Some of the prices you see may have been rounded to the nearest whole number. The price you pay will be based on the original, 'non-rounded' price (although the actual difference will be tiny anyway).</p> </div> </div> </div></div></div> </div> 
<?php include __DIR__ . '/includes/footer.php'; ?>
